apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CloudOps-Cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 50
    ssh:
      allow: false
    